export const REVIEW_CONSTANTS = {
  RATING_MIN: 1,
  RATING_MAX: 5,
  BODY_MIN_LENGTH: 1,
  BODY_MAX_LENGTH: 2000,
  PRO_CON_ITEM_MIN_LENGTH: 1,
  PRO_CON_ITEM_MAX_LENGTH: 200,
  PRO_CON_MAX_ITEMS: 10,
} as const;
